/*
 To change this license header, choose License Headers in Project Properties.
 To change this template file, choose Tools | Templates
 and open the template in the editor.
 */
package couk.deanreid.scotiaairlines;

/**

 @author Dean D. Reid
 */
public class ModernUI extends javax.swing.JFrame {

    /**
     Creates new form ModernUI
     */
    public ModernUI() {
        initComponents();
    }

    /**
     This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel pnlBook = new javax.swing.JPanel();
        javax.swing.JLabel saLabel4 = new javax.swing.JLabel();
        javax.swing.JButton btnBack4 = new javax.swing.JButton();
        javax.swing.JButton btnExit4 = new javax.swing.JButton();
        javax.swing.JButton btnReserve = new javax.swing.JButton();
        javax.swing.JButton btnBooking = new javax.swing.JButton();
        javax.swing.JButton btnCancel = new javax.swing.JButton();
        javax.swing.JPanel pnlStatus = new javax.swing.JPanel();
        javax.swing.JLabel saLabel1 = new javax.swing.JLabel();
        javax.swing.JButton btnFlight1 = new javax.swing.JButton();
        javax.swing.JButton btnSeat1 = new javax.swing.JButton();
        javax.swing.JButton btnBack = new javax.swing.JButton();
        javax.swing.JButton btnExit2 = new javax.swing.JButton();
        javax.swing.JButton btnSeating = new javax.swing.JButton();
        javax.swing.JPanel pnlAdmin = new javax.swing.JPanel();
        javax.swing.JLabel saLabel2 = new javax.swing.JLabel();
        javax.swing.JButton btnAddFlight = new javax.swing.JButton();
        javax.swing.JButton btnChangeFS = new javax.swing.JButton();
        javax.swing.JButton btnBack1 = new javax.swing.JButton();
        javax.swing.JButton btnExit3 = new javax.swing.JButton();
        javax.swing.JButton btnDeleteFlight = new javax.swing.JButton();
        javax.swing.JPanel pnlSelectFlight = new javax.swing.JPanel();
        javax.swing.JLabel saLabel3 = new javax.swing.JLabel();
        javax.swing.JButton btnBack2 = new javax.swing.JButton();
        javax.swing.JScrollPane pnlFlightList = new javax.swing.JScrollPane();
        javax.swing.JButton btnBack3 = new javax.swing.JButton();
        javax.swing.JPanel pnlPasengerInfo = new javax.swing.JPanel();
        javax.swing.JLabel saLabel5 = new javax.swing.JLabel();
        javax.swing.JButton btnExit5 = new javax.swing.JButton();
        javax.swing.JButton btnBack5 = new javax.swing.JButton();
        javax.swing.JRadioButton btnBusinessPassenger = new javax.swing.JRadioButton();
        javax.swing.JRadioButton btnOrdinaryPassenger = new javax.swing.JRadioButton();
        javax.swing.JRadioButton btnIslandPassenger = new javax.swing.JRadioButton();
        javax.swing.JLabel saPassengerNameLabel = new javax.swing.JLabel();
        javax.swing.JTextField txtPassengerName = new javax.swing.JTextField();
        javax.swing.JCheckBox btnOrdinaryPromotion = new javax.swing.JCheckBox();
        javax.swing.JLabel saIslandNameLabel = new javax.swing.JLabel();
        javax.swing.JLabel saBusinessNameLabel = new javax.swing.JLabel();
        javax.swing.JTextField txtIslandName = new javax.swing.JTextField();
        javax.swing.JTextField txtBusinessName = new javax.swing.JTextField();
        javax.swing.JButton btnBack6 = new javax.swing.JButton();
        javax.swing.JPanel pnlFlightInfo = new javax.swing.JPanel();
        javax.swing.JButton btnBack7 = new javax.swing.JButton();
        javax.swing.JLabel saLabel6 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea1 = new javax.swing.JTextArea();
        javax.swing.JPanel pnlSeatInfo = new javax.swing.JPanel();
        javax.swing.JButton btnBack8 = new javax.swing.JButton();
        javax.swing.JLabel saLabel7 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea2 = new javax.swing.JTextArea();
        javax.swing.JLabel imgBooked = new javax.swing.JLabel();
        javax.swing.JLabel imgReserved = new javax.swing.JLabel();
        javax.swing.JLabel imgFree = new javax.swing.JLabel();
        javax.swing.JButton btnSelectSeat = new javax.swing.JButton();
        javax.swing.JButton btnExit = new javax.swing.JButton();
        javax.swing.JButton btnFA = new javax.swing.JButton();
        javax.swing.JButton btnStatus = new javax.swing.JButton();
        javax.swing.JButton btnBook = new javax.swing.JButton();
        javax.swing.JLabel saLabel = new javax.swing.JLabel();

        pnlBook.setBackground(new java.awt.Color(255, 255, 255));
        pnlBook.setName("pnlBook"); // NOI18N

        saLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbico.png"))); // NOI18N
        saLabel4.setName("saLabel4"); // NOI18N

        btnBack4.setText("Back");
        btnBack4.setName("btnBack4"); // NOI18N

        btnExit4.setText("Exit");
        btnExit4.setName("btnExit4"); // NOI18N

        btnReserve.setBackground(new java.awt.Color(255, 255, 255));
        btnReserve.setText("Reserve Seat");
        btnReserve.setBorder(null);
        btnReserve.setName("btnReserve"); // NOI18N

        btnBooking.setBackground(new java.awt.Color(255, 255, 255));
        btnBooking.setText("Book Seat");
        btnBooking.setBorder(null);
        btnBooking.setName("btnBooking"); // NOI18N

        btnCancel.setText("Cancel Reservation/Booking");
        btnCancel.setName("btnCancel"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlBookLayout = new org.jdesktop.layout.GroupLayout(pnlBook);
        pnlBook.setLayout(pnlBookLayout);
        pnlBookLayout.setHorizontalGroup(
            pnlBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlBookLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlBookLayout.createSequentialGroup()
                        .add(btnBack4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnExit4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlBookLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(btnReserve, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnBooking, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(12, 12, 12))
                    .add(pnlBookLayout.createSequentialGroup()
                        .add(pnlBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(saLabel4))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlBookLayout.setVerticalGroup(
            pnlBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlBookLayout.createSequentialGroup()
                .add(7, 7, 7)
                .add(saLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnReserve, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .add(btnBooking, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnCancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(26, 26, 26)
                .add(pnlBookLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBack4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnExit4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlStatus.setName("pnlStatus"); // NOI18N

        saLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbico.png"))); // NOI18N
        saLabel1.setName("saLabel1"); // NOI18N

        btnFlight1.setText("Check Flight Status");
        btnFlight1.setName("btnFlight1"); // NOI18N

        btnSeat1.setText("Check Seat Status");
        btnSeat1.setName("btnSeat1"); // NOI18N

        btnBack.setText("Back");
        btnBack.setName("btnBack"); // NOI18N

        btnExit2.setText("Exit");
        btnExit2.setName("btnExit2"); // NOI18N

        btnSeating.setText("Show Seating Plan");
        btnSeating.setName("btnSeating"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlStatusLayout = new org.jdesktop.layout.GroupLayout(pnlStatus);
        pnlStatus.setLayout(pnlStatusLayout);
        pnlStatusLayout.setHorizontalGroup(
            pnlStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlStatusLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlStatusLayout.createSequentialGroup()
                        .add(btnFlight1)
                        .add(44, 44, 44)
                        .add(btnSeat1)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(pnlStatusLayout.createSequentialGroup()
                        .add(btnBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnExit2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlStatusLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnSeating)
                .add(90, 90, 90))
            .add(pnlStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlStatusLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(saLabel1)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        pnlStatusLayout.setVerticalGroup(
            pnlStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlStatusLayout.createSequentialGroup()
                .add(116, 116, 116)
                .add(pnlStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSeat1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnFlight1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnSeating, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(pnlStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBack, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnExit2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .add(pnlStatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlStatusLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(saLabel1)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        pnlAdmin.setName("pnlAdmin"); // NOI18N

        saLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbico.png"))); // NOI18N
        saLabel2.setName("saLabel2"); // NOI18N

        btnAddFlight.setText("Add Flight");
        btnAddFlight.setName("btnAddFlight"); // NOI18N

        btnChangeFS.setText("Change Flight Status");
        btnChangeFS.setName("btnChangeFS"); // NOI18N

        btnBack1.setText("Back");
        btnBack1.setName("btnBack1"); // NOI18N

        btnExit3.setText("Exit");
        btnExit3.setName("btnExit3"); // NOI18N

        btnDeleteFlight.setText("Delete Flight");
        btnDeleteFlight.setName("btnDeleteFlight"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlAdminLayout = new org.jdesktop.layout.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlAdminLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlAdminLayout.createSequentialGroup()
                        .add(btnBack1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnExit3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlAdminLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(pnlAdminLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, saLabel2)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlAdminLayout.createSequentialGroup()
                                .add(btnAddFlight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnDeleteFlight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .add(pnlAdminLayout.createSequentialGroup()
                .add(72, 72, 72)
                .add(btnChangeFS)
                .add(0, 0, Short.MAX_VALUE))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlAdminLayout.createSequentialGroup()
                .add(saLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlAdminLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnAddFlight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .add(btnDeleteFlight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnChangeFS, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlAdminLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBack1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnExit3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSelectFlight.setName("pnlSelectFlight"); // NOI18N

        saLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbselectflight.png"))); // NOI18N
        saLabel3.setName("saLabel3"); // NOI18N

        btnBack2.setText("Back");
        btnBack2.setName("btnBack2"); // NOI18N

        pnlFlightList.setName("pnlFlightList"); // NOI18N

        btnBack3.setText("Select Flight");
        btnBack3.setName("btnBack3"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlSelectFlightLayout = new org.jdesktop.layout.GroupLayout(pnlSelectFlight);
        pnlSelectFlight.setLayout(pnlSelectFlightLayout);
        pnlSelectFlightLayout.setHorizontalGroup(
            pnlSelectFlightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlSelectFlightLayout.createSequentialGroup()
                .add(pnlSelectFlightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlSelectFlightLayout.createSequentialGroup()
                        .add(pnlSelectFlightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlSelectFlightLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(saLabel3))
                            .add(pnlSelectFlightLayout.createSequentialGroup()
                                .addContainerGap()
                                .add(pnlFlightList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 278, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlSelectFlightLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnBack2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnBack3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 208, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlSelectFlightLayout.setVerticalGroup(
            pnlSelectFlightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlSelectFlightLayout.createSequentialGroup()
                .add(saLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 85, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlFlightList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 193, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlSelectFlightLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBack3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnBack2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPasengerInfo.setName("pnlPasengerInfo"); // NOI18N

        saLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbico.png"))); // NOI18N
        saLabel5.setName("saLabel5"); // NOI18N

        btnExit5.setText("Exit");
        btnExit5.setName("btnExit5"); // NOI18N

        btnBack5.setText("Back");
        btnBack5.setName("btnBack5"); // NOI18N

        btnBusinessPassenger.setText("Business");
        btnBusinessPassenger.setName("btnBusinessPassenger"); // NOI18N

        btnOrdinaryPassenger.setText("Ordinary");
        btnOrdinaryPassenger.setName("btnOrdinaryPassenger"); // NOI18N

        btnIslandPassenger.setText("Islander");
        btnIslandPassenger.setName("btnIslandPassenger"); // NOI18N

        saPassengerNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saPassengerNameLabel.setText("Name:");
        saPassengerNameLabel.setName("saPassengerNameLabel"); // NOI18N

        txtPassengerName.setName("txtPassengerName"); // NOI18N

        btnOrdinaryPromotion.setText("Promotion?");
        btnOrdinaryPromotion.setName("btnOrdinaryPromotion"); // NOI18N

        saIslandNameLabel.setText("Island Name:");
        saIslandNameLabel.setName("saIslandNameLabel"); // NOI18N

        saBusinessNameLabel.setText("Business Name:");
        saBusinessNameLabel.setName("saBusinessNameLabel"); // NOI18N

        txtIslandName.setText("Insert Name");
        txtIslandName.setName("txtIslandName"); // NOI18N

        txtBusinessName.setText("Insert Name");
        txtBusinessName.setName("txtBusinessName"); // NOI18N

        btnBack6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack6.setText("Submit Details");
        btnBack6.setName("btnBack6"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlPasengerInfoLayout = new org.jdesktop.layout.GroupLayout(pnlPasengerInfo);
        pnlPasengerInfo.setLayout(pnlPasengerInfoLayout);
        pnlPasengerInfoLayout.setHorizontalGroup(
            pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlPasengerInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlPasengerInfoLayout.createSequentialGroup()
                        .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlPasengerInfoLayout.createSequentialGroup()
                                .add(saIslandNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(txtIslandName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(btnBusinessPassenger)
                            .add(pnlPasengerInfoLayout.createSequentialGroup()
                                .add(saBusinessNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 79, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(btnBack6)
                                    .add(txtBusinessName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(pnlPasengerInfoLayout.createSequentialGroup()
                        .add(btnBack5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnExit5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(pnlPasengerInfoLayout.createSequentialGroup()
                        .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(pnlPasengerInfoLayout.createSequentialGroup()
                                .add(saPassengerNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(txtPassengerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlPasengerInfoLayout.createSequentialGroup()
                                .add(btnIslandPassenger)
                                .add(23, 23, 23)))
                        .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(btnOrdinaryPassenger)
                            .add(btnOrdinaryPromotion))
                        .addContainerGap(23, Short.MAX_VALUE))))
            .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlPasengerInfoLayout.createSequentialGroup()
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(saLabel5)
                    .addContainerGap()))
        );
        pnlPasengerInfoLayout.setVerticalGroup(
            pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlPasengerInfoLayout.createSequentialGroup()
                .add(116, 116, 116)
                .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saPassengerNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtPassengerName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnOrdinaryPromotion))
                .add(18, 18, 18)
                .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBusinessPassenger)
                    .add(btnIslandPassenger)
                    .add(btnOrdinaryPassenger))
                .add(18, 18, 18)
                .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(saIslandNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtIslandName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(saBusinessNameLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtBusinessName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE)
                .add(btnBack6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnBack5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnExit5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .add(pnlPasengerInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(pnlPasengerInfoLayout.createSequentialGroup()
                    .addContainerGap()
                    .add(saLabel5)
                    .addContainerGap(273, Short.MAX_VALUE)))
        );

        pnlFlightInfo.setName("pnlFlightInfo"); // NOI18N

        btnBack7.setText("Back");
        btnBack7.setName("btnBack7"); // NOI18N

        saLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbico.png"))); // NOI18N
        saLabel6.setName("saLabel6"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Flight Into Here ");
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout pnlFlightInfoLayout = new org.jdesktop.layout.GroupLayout(pnlFlightInfo);
        pnlFlightInfo.setLayout(pnlFlightInfoLayout);
        pnlFlightInfoLayout.setHorizontalGroup(
            pnlFlightInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlFlightInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlFlightInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlFlightInfoLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(saLabel6))
                    .add(jScrollPane1))
                .addContainerGap())
            .add(pnlFlightInfoLayout.createSequentialGroup()
                .add(88, 88, 88)
                .add(btnBack7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFlightInfoLayout.setVerticalGroup(
            pnlFlightInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlFlightInfoLayout.createSequentialGroup()
                .add(saLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btnBack7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7))
        );

        pnlSeatInfo.setName("pnlSeatInfo"); // NOI18N

        btnBack8.setText("Back");
        btnBack8.setName("btnBack8"); // NOI18N

        saLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbico.png"))); // NOI18N
        saLabel7.setName("saLabel7"); // NOI18N

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Insert Seat Plan Here");
        jTextArea2.setName("jTextArea2"); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        imgBooked.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/seatBooked.png"))); // NOI18N
        imgBooked.setText("Booked");
        imgBooked.setName("imgBooked"); // NOI18N

        imgReserved.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/seatReserved.png"))); // NOI18N
        imgReserved.setText("Reserved");
        imgReserved.setName("imgReserved"); // NOI18N

        imgFree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/seatFree.png"))); // NOI18N
        imgFree.setText("Free");
        imgFree.setName("imgFree"); // NOI18N

        btnSelectSeat.setText("Select Seat");
        btnSelectSeat.setName("btnSelectSeat"); // NOI18N

        org.jdesktop.layout.GroupLayout pnlSeatInfoLayout = new org.jdesktop.layout.GroupLayout(pnlSeatInfo);
        pnlSeatInfo.setLayout(pnlSeatInfoLayout);
        pnlSeatInfoLayout.setHorizontalGroup(
            pnlSeatInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlSeatInfoLayout.createSequentialGroup()
                .add(pnlSeatInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlSeatInfoLayout.createSequentialGroup()
                        .add(60, 60, 60)
                        .add(saLabel7)
                        .add(0, 75, Short.MAX_VALUE))
                    .add(pnlSeatInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(pnlSeatInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2)
                            .add(pnlSeatInfoLayout.createSequentialGroup()
                                .add(imgFree)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(imgReserved)
                                .add(82, 82, 82)
                                .add(imgBooked)
                                .add(21, 21, 21))
                            .add(org.jdesktop.layout.GroupLayout.LEADING, pnlSeatInfoLayout.createSequentialGroup()
                                .add(btnBack8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(btnSelectSeat, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlSeatInfoLayout.setVerticalGroup(
            pnlSeatInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlSeatInfoLayout.createSequentialGroup()
                .addContainerGap()
                .add(saLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlSeatInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(imgFree)
                    .add(imgReserved)
                    .add(imgBooked))
                .add(18, 18, 18)
                .add(pnlSeatInfoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(btnBack8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .add(btnSelectSeat, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("saFrameMain"); // NOI18N
        getContentPane().setLayout(null);

        btnExit.setText("Exit");
        btnExit.setName("btnExit"); // NOI18N
        getContentPane().add(btnExit);
        btnExit.setBounds(168, 271, 100, 60);

        btnFA.setText("Administration");
        btnFA.setName("btnFA"); // NOI18N
        getContentPane().add(btnFA);
        btnFA.setBounds(10, 271, 110, 60);

        btnStatus.setText("Check Status");
        btnStatus.setName("btnStatus"); // NOI18N
        getContentPane().add(btnStatus);
        btnStatus.setBounds(31, 193, 220, 60);

        btnBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBook.setText("Book Flight");
        btnBook.setName("btnBook"); // NOI18N
        getContentPane().add(btnBook);
        btnBook.setBounds(31, 111, 220, 60);

        saLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tbico.png"))); // NOI18N
        saLabel.setName("saLabel"); // NOI18N
        getContentPane().add(saLabel);
        saLabel.setBounds(0, 0, 278, 85);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModernUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModernUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModernUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModernUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModernUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
